### ISSUE TITLE
Update github actions to use caching/not set up the environment every time

### ISSUE THREAD

**Issue by kaijagahm** [carpentries-incubator/R-help-reprexes#34]
Let's see if we can make the website build a little faster...

**Comment by jnywong** [comment]
This takes a bit of work, but you could pre-build a container image with all of your software requirements and pull that into the GHA:

- https://dev.to/mikerogers0/using-docker-to-speed-up-my-github-action-2333
- https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/running-jobs-in-a-container

I would suggest publishing with a container registry such as quay.io or even GitHub's own container registry rather than DockerHub.

**Comment by kaijagahm** [comment]
Thanks @jnywong, just seeing this now (still getting comfortable with GitHub, evidently!)

I think this is more work than we want to get into right now, but it's good to be aware that the option exists.
